// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext, StoryblokTable } from '../storyblok.d.ts';
export interface StoryblokBanner {
  headline?: string;
  subheading?: string;
  backgroundImage?: StoryblokAsset;
  component: "banner";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokButton {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  text?: string;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokButtonAmadeu {
  label?: string;
  website?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "button_amadeu";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokCheckbox {
  label?: string;
  component: "checkbox";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokCtaBanner {
  title?: string;
  description?: string;
  ctaText?: string;
  ctaLink?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  image?: StoryblokAsset;
  formEmbedCode?: string;
  backgroundColor?:
    | ""
    | "blue-agave"
    | "blueberry"
    | "roasted-chestnut"
    | "dino-kale"
    | "oat-milk"
    | "oyster"
    | "peri-peri"
    | "ube"
    | "yuzu";
  alignment?: "" | "centered" | "split";
  variant?: "" | "centered-text" | "split-layout,";
  component: "cta_banner";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokDatePicker {
  label?: string;
  month_placeholder?: string;
  day_placeholder?: string;
  year_placeholder?: string;
  component: "date_picker";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokDropdown {
  component: "Dropdown";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokFooter {
  companyName?: string;
  byline?: string;
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokHero {
  hero_image?: StoryblokAsset;
  hero_title?: string;
  hero_subtitle?: string;
  component: "hero";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokInputEmail {
  label?: string;
  suffix?: string;
  component: "input_email";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokNavbar {
  logo?: StoryblokAsset;
  component: "navbar";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokNumberInput {
  label: string;
  suffix?: string;
  component: "number_input";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokPage {
  navbar?: ISbStoryData<StoryblokNavbar> | string;
  body?: (
    | StoryblokBanner
    | StoryblokButton
    | StoryblokButtonAmadeu
    | StoryblokCheckbox
    | StoryblokCtaBanner
    | StoryblokDatePicker
    | StoryblokDropdown
    | StoryblokFooter
    | StoryblokHero
    | StoryblokInputEmail
    | StoryblokNavbar
    | StoryblokNumberInput
    | StoryblokPage
    | StoryblokPageTestAmadeu
    | StoryblokQuizPageType1
    | StoryblokSimplePage
    | StoryblokTest
    | StoryblokTestimonial
    | StoryblokTestimonialSection
    | StoryblokText
    | StoryblokWhyThisMatters
  )[];
  footer: ISbStoryData<StoryblokFooter> | string;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokPageTestAmadeu {
  teste1: string;
  teste2?: StoryblokTable;
  teste3?: {
    [k: string]: unknown;
  }[];
  custom_block?: (
    | StoryblokBanner
    | StoryblokButton
    | StoryblokButtonAmadeu
    | StoryblokCheckbox
    | StoryblokCtaBanner
    | StoryblokDatePicker
    | StoryblokDropdown
    | StoryblokFooter
    | StoryblokHero
    | StoryblokInputEmail
    | StoryblokNavbar
    | StoryblokNumberInput
    | StoryblokPage
    | StoryblokPageTestAmadeu
    | StoryblokQuizPageType1
    | StoryblokSimplePage
    | StoryblokTest
    | StoryblokTestimonial
    | StoryblokTestimonialSection
    | StoryblokText
    | StoryblokWhyThisMatters
  )[];
  component: "page-test-amadeu";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokQuizPageType1 {
  body?: (
    | StoryblokBanner
    | StoryblokButton
    | StoryblokButtonAmadeu
    | StoryblokCheckbox
    | StoryblokCtaBanner
    | StoryblokDatePicker
    | StoryblokDropdown
    | StoryblokFooter
    | StoryblokHero
    | StoryblokInputEmail
    | StoryblokNavbar
    | StoryblokNumberInput
    | StoryblokPage
    | StoryblokPageTestAmadeu
    | StoryblokQuizPageType1
    | StoryblokSimplePage
    | StoryblokTest
    | StoryblokTestimonial
    | StoryblokTestimonialSection
    | StoryblokText
    | StoryblokWhyThisMatters
  )[];
  component: "quiz-page-type1";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokSimplePage {
  body?: (
    | StoryblokBanner
    | StoryblokButton
    | StoryblokButtonAmadeu
    | StoryblokCheckbox
    | StoryblokCtaBanner
    | StoryblokDatePicker
    | StoryblokDropdown
    | StoryblokFooter
    | StoryblokHero
    | StoryblokInputEmail
    | StoryblokNavbar
    | StoryblokNumberInput
    | StoryblokPage
    | StoryblokPageTestAmadeu
    | StoryblokQuizPageType1
    | StoryblokSimplePage
    | StoryblokTest
    | StoryblokTestimonial
    | StoryblokTestimonialSection
    | StoryblokText
    | StoryblokWhyThisMatters
  )[];
  component: "simple-page";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTest {
  component: "Test";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTestimonial {
  author?: string;
  body?: StoryblokRichtext;
  component: "testimonial";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokTestimonialSection {
  heading?: string;
  subheading?: string;
  testimonials?: (ISbStoryData<StoryblokTestimonial> | string)[];
  component: "testimonialSection";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokText {
  content?: string;
  component: "text";
  _uid: string;
  [k: string]: unknown;
}

export interface StoryblokWhyThisMatters {
  title: string;
  description: string;
  component: "why_this_matters";
  _uid: string;
  [k: string]: unknown;
}
